version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - clientvol:/clientdata
    networks:
      - my_network
    image: dice_devops_final_client  

volumes:
  clientvol:

networks:
  my_network:
    external: true
